config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]
  resources :menus
  devise_for :users
  # devise_for :users
  root 'welcome#index'
  get 'welcome/show', 'welcome#show'
  post '/', to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    @amount = 500

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index

  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_menu
      @menu = Menu.find(params[:id])
    end


    def menu_params
      params.fetch(:menu, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :address_search]
  def index
    unless params[:search].nil?
      p params[:search]
      @places = GoogleMapsService.nearby_places params[:search]
      @meals =  Unsplash::Photo.search("food")
      @local_resturants = @places.map do |r|
        pd = GoogleMapsService.place_details(r['place_id'])['result']
        {
          id: r['place_id'],
          name: r['name'],
          opening_hours: r['opening_hours'],
          details: {
            types: pd['types'],
            vicinity: pd['vicinity']
          }
        }
      end
    end
    Rails.logger.info @places
  end

  def show
    @places = GoogleMapsService.nearby_places
    Rails.logger.info @places
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/application/_bootsrapcss.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

app/views/application/_bootstrap.html.erb
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

app/views/application/_bootstrap_css.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

app/views/application/_font_awesome_css.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

app/views/application/_fonts.html.erb
<style>
@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i|Roboto');
</style>
<!-- fonts.google.com -->

app/views/application/_footer.html.erb
<footer>
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col">
          <!-- Trigger the modal with a button -->
          <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal123">Contact us</button>
        </div>
        <div class="col">
          <!-- Trigger the modal with a button -->
          <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal124">About</button>
        </div>
        <div class="col">
          <!-- Trigger the modal with a button -->
          <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal125">Press</button>
        </div>
        <div class="col">
          ©2018 Foodé
        </div>
      </div>
    </div>
  </div>
</footer>

<div id="myModal123" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Contact Us</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <p>
  Send us an email:
  <a href="mailto:someone@example.com?Subject=Hello%20again" target="_top"><i class="fa fa-envelope-square"></i>
  </a>
  </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="myModal124" class="modal fade" role="dialog">
  <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">About Foodé</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
  </div>
</div>

<div id="myModal125" class="modal fade" role="dialog">
  <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Press</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
  </div>
</div>

app/views/application/_gsap.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>

<!-- Benefits
Up to 20x faster than jQuery's native animate() method. See the interactive speed comparison for yourself.
Works exactly the same as the regular jQuery.animate() method. Same syntax. No need to change your code. Just load the plugin (and TweenMax or TweenLite & CSSPlugin) and you're done. -->

app/views/application/_header.html.erb
<header>
  <div class="tp-background">
    <div class="header">
      <div class="container">
        <div class="row">
          <div class="col-1">
            <%= link_to root_path do %>
            <div class="logo">
              <%= image_tag "logo-f.png" %>
              <% end %>
            </div>
          </div>
          <!-- <div class="col-8">
            <h2 id="foode">FOODÉ</h2>
          </div> -->
          <div class="col-3">
            <!-- <ul class="hmenu"> -->
              <%= render 'devise/menu/registration_items' %>
              <%= render 'devise/menu/login_items' %>
            <!-- </ul> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/application/_jquery.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

app/views/application/_meta.html.erb
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="discription" content="Foodé Dynamic Local Resturant Menu"/>
<meta name="keywords" content="delivery, fast food, food near me, delivery near me, diet fast food"/>
<meta name="robots" content="follow, index, archive"/>
<meta name="author" content="Bruce Lesko"/>
<%= favicon_link_tag 'logo-f-transparent.png' %>

app/views/application/_navigation.html.erb
<div class="container navigation">
  <div class="row justify-content-center">
    <div class="col">
      <!-- <i class="fas fa-map-marker"></i> -->
    </div>
    <div class="col">
    </div>
    <div class="col">
      <!-- <form>
      	<input type="search" placeholder="Address...">
      </form> -->
<%=form_tag "/" do %>
      <input type="search" name="search" placeholder="Address..">
      <%# submit_tag "Search" %>
      <% end %>
    </div>
    <div class="col">
      <div class="dropdown">
        <button class="dropbtn">ORDER TYPE</button>
        <div class="dropdown-content">
          <a href="#">Delivery</a>
          <a href="#">Pickup</a>
          <a href="#">Eat-in</a>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="dropdown">
        <button class="dropbtn">FILTER</button>
        <div class="dropdown-content">
          <ul id="horizontal-list">
            <li><a href="#">Cheap $</a></li>
            <li><a href="#">Under $10</a></li>
            <li><a href="#">Over $10</a></li>
            <li><a href="#">Expensive $$$</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="dropdown">
        <button class="dropbtn">FAVORITES</button>
        <div class="dropdown-content">
          <a href="#">Cofee Shops</a>
          <a href="#">Pizza</a>
          <a href="#">Vegaterian</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charges/create.html.erb
<h3>Thanks, you paid <strong>$5.00</strong>!</h3>

app/views/charges/new.html.erb
<!-- app/views/charges/new.html.erb -->

<div class="center">
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <h3>Subscribe to Foodé for only 5$/month!</h3>
        <br>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Foode"
            data-amount="500"
            data-locale="auto"></script>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foode</title>
    <%= csrf_meta_tags %>
    <%= render 'meta' %>
    <%= render 'jquery' %>
    <%= render 'gsap' %>
    <%= render 'bootstrap_css' %>
    <%= render 'font_awesome_css' %>
    <%= render 'fonts' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'bootstrap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'header' %>
    <%= render 'navigation' %>
    <%= yield %>
    <%= render 'footer' %>
    <%# console %>
  </body>

</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<section id="photos">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">
  <img src="https://placeimg.com/640/480/animals" alt="Cute cat">

</section>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>
<h1>test</h1>

app/views/welcome/_meals.html.erb
<% @meals = search_results = %>
<% Unsplash::Photo.search("food").sample["urls"]["small"] %>

app/views/welcome/_show.html.erb
<section id="photos">

  <% @local_resturants[0..9].each do |restaurant| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="<%= @meals.sample["urls"]["small"] %>'" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"> <%= restaurant[:name] %></h5>
        <a href="#" class="btn btn-primary"> Details</a>
      </div>
    </div>
  <% end %>
</section>



<!-- id: r['place_id'],
name: r['name'],
opening_hours: r['opening_hours'],
details: {
  types: pd['types'],
  vicinity: pd['vicinity']
} -->

app/views/welcome/index.html.erb
<div class="container welcome">
  <% if @local_resturants.nil? %>
  <div class="col-8">
    <h2 id="foode">FOODÉ</h2>
  </div>
    <div class="container">
      <div class="row">
        <h2>
          <i class="fas fa-search"></i>
          Search for your favorite food!
        </h2>
      </div>
      <div class="row">
        <h2>
          <i class="fas fa-map-marker"></i>
          See all the local menus!
        </h2>
      </div>
      <div class="row">
        <h2>
          <i class="fas fa-filter"></i>
          Filter by your favorite types or diet requirments!
        </h2>
      </div>
    </div>
    <hr class="my-4">
    <div class="signup">
      <p class="lead">
        <!-- <%= link_to('Sign Up', new_user_registration_path, class: 'btn btn-success btn-lg', title: 'Sign UP') %> -->
        <%= link_to('Subscribe', new_charge_path, class: 'btn btn-success btn-lg') %>
        

      </p>
    </div>
  </div>
<% else %>
  <%= render 'show' %>
<% end %>